"""initial schema

Revision ID: 440544c930c1
Revises:
Create Date: 2026-08-27 00:06:28.729191
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import ansari.api.models


revision: str = "440544c930c1"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", ansari.api.models.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("repo_url", sa.String(length=500), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=True)
    op.create_table(
        "environments",
        sa.Column("id", ansari.api.models.UUID(), nullable=False),
        sa.Column("project_id", ansari.api.models.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("cluster", sa.String(length=100), nullable=False),
        sa.Column("namespace", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("id", ansari.api.models.UUID(), nullable=False),
        sa.Column("project_id", ansari.api.models.UUID(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "RUNNING", "SUCCEEDED", "FAILED", name="pipeline_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deployments",
        sa.Column("id", ansari.api.models.UUID(), nullable=False),
        sa.Column("environment_id", ansari.api.models.UUID(), nullable=False),
        sa.Column("pipeline_run_id", ansari.api.models.UUID(), nullable=False),
        sa.Column("image_tag", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "DEPLOYING", "HEALTHY", "FAILED", "ROLLED_BACK", name="deployment_status"
            ),
            nullable=False,
        ),
        sa.Column("deployed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deployments")
    op.drop_table("pipeline_runs")
    op.drop_table("environments")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
