---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Apply the role under test
      ansible.builtin.include_role:
        name: "{{ lookup('ansible.builtin.env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
